### ISSUE TITLE
Print functionality is not working

### ISSUE THREAD

**Issue by reefdog** [Hyperobjekt/bil-map#43]
Clicking PRINT on a production build triggers the following error in the console:

In Firefox:
```
Uncaught TypeError: e.cell.textPos is undefined
    didDrawCell printPDF.js:286
    callCellHooks jspdf.plugin.autotable.js:1163
    p jspdf.plugin.autotable.js:1788
    h jspdf.plugin.autotable.js:1749
    h jspdf.plugin.autotable.js:1760
    drawTable jspdf.plugin.autotable.js:1593
    drawTable jspdf.plugin.autotable.js:1591
    autoTable jspdf.plugin.autotable.js:104
    L printPDF.js:261
    value ExportFooter.js:18
    onClick ExportFooter.js:66
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
printPDF.js:286:20
```

In Chrome:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at didDrawCell (printPDF.js:286:39)
    at t.callCellHooks (jspdf.plugin.autotable.js:1162:38)
    at p (jspdf.plugin.autotable.js:1788:15)
    at h (jspdf.plugin.autotable.js:1749:9)
    at jspdf.plugin.autotable.js:1593:13
    at Array.forEach (<anonymous>)
    at e.drawTable (jspdf.plugin.autotable.js:1591:20)
    at t.API.autoTable (jspdf.plugin.autotable.js:104:27)
    at L (printPDF.js:261:7)
    at t.value (ExportFooter.js:18:5)
```

**Comment by reefdog** [comment]
I've confirmed that this worked as of 74085a62b8b5799263cc1ff0a30649631c60e664 and stopped working in a907f8d38acf3fc9adec85387cf7f231f5fbbc0d. It looks like one of the dependency updates may have broken PDF generation. Diving in further…

**Comment by reefdog** [comment]
Figured it out!

That commit upgraded several of our dependencies, including jsPDF-AutoTable. That library made a [breaking change](https://github.com/simonbengtsson/jsPDF-AutoTable/commit/5a4b737384d226aa56f9dbc711e9e7bd30aa3d18) in [v3.5.4](https://github.com/simonbengtsson/jsPDF-AutoTable/releases/tag/v3.5.4), replacing the `textPos` attribute we were using with a `getTextPos()` method to generate the same values.

I'll patch our JS shortly with a fix.
